[target.thumbv7em-none-eabihf]
# runner = "arm-none-eabi-gdb -q"
# first start openocd:
#   openocd -f interface/stlink.cfg -f target/stm32f3x.cfg
runner = "gdb-multiarch -q -x ../openocd.gdb"
# runner = "gdb -q"
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7em-none-eabihf"

